def init
  LibVips.vips_object_get_type
  LibVips.vips_thing_get_type
  LibVips.vips_area_get_type
  LibVips.vips_save_string_get_type
  LibVips.vips_ref_string_get_type
  LibVips.vips_blob_get_type
  LibVips.vips_array_double_get_type
  LibVips.vips_array_int_get_type
  LibVips.vips_array_image_get_type
  LibVips.vips_connection_get_type
  LibVips.vips_source_get_type
  LibVips.vips_source_custom_get_type
  LibVips.vips_target_get_type
  LibVips.vips_target_custom_get_type
  LibVips.vips_sbuf_get_type
  LibVips.vips_image_get_type
  LibVips.vips_format_get_type
  LibVips.vips_region_get_type
  LibVips.vips_interpolate_get_type
  LibVips.vips_thread_state_get_type
  LibVips.vips_operation_get_type
  LibVips.vips_foreign_get_type
  LibVips.vips_foreign_load_get_type
  LibVips.vips_foreign_save_get_type
  LibVips.vips_operation_math_get_type
  LibVips.vips_operation_math2_get_type
  LibVips.vips_operation_round_get_type
  LibVips.vips_operation_relational_get_type
  LibVips.vips_operation_boolean_get_type
  LibVips.vips_operation_complex_get_type
  LibVips.vips_operation_complex2_get_type
  LibVips.vips_operation_complexget_get_type
  LibVips.vips_precision_get_type
  LibVips.vips_intent_get_type
  LibVips.vips_pcs_get_type
  LibVips.vips_extend_get_type
  LibVips.vips_compass_direction_get_type
  LibVips.vips_direction_get_type
  LibVips.vips_align_get_type
  LibVips.vips_angle_get_type
  LibVips.vips_angle45_get_type
  LibVips.vips_interesting_get_type
  LibVips.vips_blend_mode_get_type
  LibVips.vips_combine_get_type
  LibVips.vips_combine_mode_get_type
  LibVips.vips_foreign_flags_get_type
  LibVips.vips_fail_on_get_type
  LibVips.vips_saveable_get_type
  LibVips.vips_foreign_subsample_get_type
  LibVips.vips_foreign_jpeg_subsample_get_type
  LibVips.vips_foreign_webp_preset_get_type
  LibVips.vips_foreign_tiff_compression_get_type
  LibVips.vips_foreign_tiff_predictor_get_type
  LibVips.vips_foreign_tiff_resunit_get_type
  LibVips.vips_foreign_png_filter_get_type
  LibVips.vips_foreign_ppm_format_get_type
  LibVips.vips_foreign_dz_layout_get_type
  LibVips.vips_foreign_dz_depth_get_type
  LibVips.vips_foreign_dz_container_get_type
  LibVips.vips_foreign_heif_compression_get_type
  LibVips.vips_demand_style_get_type
  LibVips.vips_image_type_get_type
  LibVips.vips_interpretation_get_type
  LibVips.vips_band_format_get_type
  LibVips.vips_coding_get_type
  LibVips.vips_access_get_type
  LibVips.vips_operation_morphology_get_type
  LibVips.vips_argument_flags_get_type
  LibVips.vips_operation_flags_get_type
  LibVips.vips_region_shrink_get_type
  LibVips.vips_kernel_get_type
  LibVips.vips_size_get_type
  LibVips.vips_token_get_type
end

init
